export class StandardEquipment{
    standardEquipmentID: number;
    threeXThreePointRearSeatBelts: boolean;
    abs: boolean;
    alarm: boolean;
    alloyWheels: boolean;
    bodyColouredBumpers: boolean;
    cruiseControl: boolean;
    driversAirbags: boolean;
    electricDriversSeat: boolean;
    electricMirrors: boolean;
    electricPassengerSeat: boolean;
    electricRoof: boolean;
    foldingRearSeats: boolean;
    frontElectricWindows: boolean;
    heightAdjustableDriversSeat: boolean; 
    isofixChildSeatAnchorPoints: boolean;
    leatherSeatTrim: boolean;
    parkingSensors: boolean;
    pas: boolean;
    passengersAirbags: boolean;
    remote: boolean;
    rearElectricWindows: boolean;
    remoteLocking: boolean;
    satNav: boolean;
    sideAirbags: boolean;
    streeingWheelRakeAdjustment: boolean;
    steeringWheelReachAdjustment: boolean;
}